import { z } from "zod";
import type { Endpoint } from "./router";

/**
 * The endpoint reference in API.md, generated from the endpoint definitions
 * so the guide cannot drift from the code: tests/api-reference.test.ts fails
 * when API.md differs, and `npm run api:docs` rewrites it.
 */

export const REFERENCE_START = "<!-- endpoint-reference:start (generated by npm run api:docs; do not edit by hand) -->";
export const REFERENCE_END = "<!-- endpoint-reference:end -->";

type JsonSchema = {
  type?: string | string[];
  $ref?: string;
  properties?: Record<string, JsonSchema>;
  required?: string[];
  description?: string;
  enum?: unknown[];
  items?: JsonSchema;
  anyOf?: JsonSchema[];
  format?: string;
  default?: unknown;
  id?: string;
};

const toJson = (schema: z.ZodType) =>
  z.toJSONSchema(schema, { io: "input", unrepresentable: "any", target: "draft-2020-12" }) as JsonSchema & { $defs?: Record<string, JsonSchema> };

/** A short type name: string, integer, Money, "a" | "b", array of X. */
function typeOf(s: JsonSchema, defs: Record<string, JsonSchema> = {}): string {
  if (s.$ref) return s.$ref.split("/").pop()!;
  if (s.id) return s.id;
  if (s.enum) return s.enum.map((v) => `\`${String(v)}\``).join(" \\| ");
  if (s.anyOf) {
    const parts = s.anyOf.filter((p) => p.type !== "null").map((p) => typeOf(p, defs));
    return parts.join(" or ") + (s.anyOf.some((p) => p.type === "null") ? ", or null" : "");
  }
  if (s.type === "array" && s.items) return `array of ${typeOf(s.items, defs)}`;
  if (Array.isArray(s.type)) return s.type.filter((t) => t !== "null").join(" or ") + (s.type.includes("null") ? ", or null" : "");
  if (s.format === "date") return "date";
  if (s.format === "date-time") return "timestamp";
  return s.type ?? "any";
}

const cell = (text: string) => text.replace(/\|/g, "\\|").replace(/\n+/g, " ");

function fieldTable(schema: JsonSchema, heading: string): string[] {
  const props = Object.entries(schema.properties ?? {});
  if (props.length === 0) return [];
  const required = new Set(schema.required ?? []);
  return [
    `| ${heading} | Type | Required | Notes |`,
    "| --- | --- | --- | --- |",
    ...props.map(([name, p]) => {
      const notes = [p.description ?? "", p.default !== undefined && p.default !== null ? `Default \`${JSON.stringify(p.default)}\`.` : ""]
        .filter(Boolean)
        .join(" ");
      return `| \`${name}\` | ${cell(typeOf(p))} | ${required.has(name) && p.default === undefined ? "yes" : ""} | ${cell(notes)} |`;
    }),
    "",
  ];
}

const anchor = (e: Endpoint) => `${e.method}-${e.path}`.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

export type Catalogues = {
  scopes: Record<string, string>;
  events: Record<string, { scope: string; description: string }>;
  problems: Record<string, string>;
  statuses: Record<string, number>;
};

export function endpointReference(endpoints: Endpoint[], c: Catalogues): string {
  const tags = [...new Set(endpoints.map((e) => e.tag))];
  const out: string[] = [];

  out.push("### Scopes", "", "| Scope | Lets the client |", "| --- | --- |");
  for (const [scope, text] of Object.entries(c.scopes)) out.push(`| \`${scope}\` | ${cell(text)} |`);
  out.push("", "### Event types", "", "| Type | Needs | Means |", "| --- | --- | --- |");
  for (const [type, e] of Object.entries(c.events)) out.push(`| \`${type}\` | \`${e.scope}\` | ${cell(e.description)} |`);
  out.push("", "### Error codes", "", "| Code | Status | Means |", "| --- | --- | --- |");
  for (const [code, text] of Object.entries(c.problems)) out.push(`| <a id="problem-${code}"></a>\`${code}\` | ${c.statuses[code]} | ${cell(text)} |`);
  out.push("", "### Endpoints", "");

  out.push("| Method | Path | Scopes | What it does |", "| --- | --- | --- | --- |");
  for (const e of endpoints) {
    const scopes = e.public ? "none (public)" : e.scopes.length ? e.scopes.map((s) => `\`${s}\``).join(" + ") : "any token";
    out.push(`| ${e.method} | [\`${e.path}\`](#${anchor(e)}) | ${scopes} | ${cell(e.summary)} |`);
  }
  out.push("");

  for (const tag of tags) {
    out.push(`### ${tag} endpoints`, "");
    for (const e of endpoints.filter((x) => x.tag === tag)) {
      out.push(`#### ${e.method} ${e.path}`, "", `<a id="${anchor(e)}"></a>**${e.summary}.**${e.description ? ` ${e.description}` : ""}`, "");
      const facts: string[] = [];
      if (e.public) facts.push("No token needed.");
      else if (e.scopes.length) facts.push(`Needs ${e.scopes.map((s) => `\`${s}\``).join(" and ")}.`);
      else facts.push("Any valid token.");
      if (e.optionalScopes?.length) facts.push(`More fields with ${e.optionalScopes.map((s) => `\`${s}\``).join(" or ")}.`);
      if (e.idempotent) facts.push("Send an `Idempotency-Key`.");
      if (e.etag) facts.push(e.method === "GET" ? "Returns an `ETag`." : "Returns an `ETag`; honours `If-Match`.");
      facts.push(`Answers ${e.status ?? 200}.`);
      out.push(facts.join(" "), "");

      if (e.params) {
        out.push("| Path parameter | Meaning |", "| --- | --- |", ...Object.entries(e.params).map(([k, v]) => `| \`${k}\` | ${cell(v)} |`), "");
      }
      if (e.query) out.push(...fieldTable(toJson(e.query), "Query parameter"));
      if (e.body) {
        const body = toJson(e.body);
        const resolved = body.$ref && body.$defs ? (body.$defs[body.$ref.split("/").pop()!] ?? body) : body;
        out.push(...fieldTable(resolved, "Body field"));
      }
      if (e.example?.body !== undefined || e.example?.path || e.example?.query) {
        const target = `${e.example?.path ?? e.path}${e.example?.query ? `?${e.example.query}` : ""}`;
        out.push("```http", `${e.method} /api/v1${target}`);
        if (e.example?.body !== undefined) out.push("Content-Type: application/json", "", JSON.stringify(e.example.body, null, 2));
        out.push("```", "");
      }
      if (e.example?.response !== undefined) {
        out.push("```json", JSON.stringify(e.example.response, null, 2), "```", "");
      }
    }
  }
  return out.join("\n").trimEnd() + "\n";
}

/** API.md with its reference section replaced. */
export function withReference(markdown: string, reference: string): string {
  const start = markdown.indexOf(REFERENCE_START);
  const end = markdown.indexOf(REFERENCE_END);
  if (start < 0 || end < start) throw new Error("API.md has lost its endpoint-reference markers.");
  return `${markdown.slice(0, start + REFERENCE_START.length)}\n\n${reference}\n${markdown.slice(end)}`;
}
