import { z } from "zod";
import type { Endpoint } from "./router";

/**
 * The endpoint reference in API.md, generated from the endpoint definitions
 * so the guide cannot drift from the code: tests/api-reference.test.ts fails
 * when API.md differs, and `npm run api:docs` rewrites it.
 */

export const REFERENCE_START = "<!-- endpoint-reference:start (generated by npm run api:docs; do not edit by hand) -->";
export const REFERENCE_END = "<!-- endpoint-reference:end -->";

type JsonSchema = {
  type?: string | string[];
  $ref?: string;
  properties?: Record<string, JsonSchema>;
  required?: string[];
  description?: string;
  enum?: unknown[];
  items?: JsonSchema;
  anyOf?: JsonSchema[];
  format?: string;
  default?: unknown;
  id?: string;
};

const toJson = (schema: z.ZodType) =>
  z.toJSONSchema(schema, { io: "input", unrepresentable: "any", target: "draft-2020-12" }) as JsonSchema & { $defs?: Record<string, JsonSchema> };

/** The same, for what an endpoint answers rather than what it accepts. */
const toJsonOut = (schema: z.ZodType) =>
  z.toJSONSchema(schema, { io: "output", unrepresentable: "any", target: "draft-2020-12" }) as JsonSchema & { $defs?: Record<string, JsonSchema> };

const deref = (s: JsonSchema, defs: Record<string, JsonSchema>): JsonSchema =>
  s.$ref ? (defs[s.$ref.split("/").pop()!] ?? s) : s;

/**
 * A representative value for one field, from its own schema: an enum's first
 * value, a date for a date, and so on.
 *
 * Built from the schema rather than captured from a live call, for two
 * reasons: it is the same every time, so regenerating the reference never
 * churns the file; and it cannot describe a field the code does not actually
 * answer with, because the shape is the code's own.
 */
function sampleOf(schema: JsonSchema, defs: Record<string, JsonSchema>, name = "", depth = 0): unknown {
  const s = deref(schema, defs);
  if (depth > 6) return null;
  if (s.default !== undefined) return s.default;
  if (s.enum && s.enum.length > 0) return s.enum[0];
  if (s.anyOf) {
    const first = s.anyOf.find((p) => p.type !== "null");
    return first ? sampleOf(first, defs, name, depth + 1) : null;
  }
  const type = Array.isArray(s.type) ? s.type.find((t) => t !== "null") : s.type;
  if (type === "array") return s.items ? [sampleOf(s.items, defs, name, depth + 1)] : [];
  if (type === "object" || s.properties) {
    const out: Record<string, unknown> = {};
    for (const [key, prop] of Object.entries(s.properties ?? {})) out[key] = sampleOf(prop, defs, key, depth + 1);
    return out;
  }
  if (type === "boolean") return true;
  if (type === "integer" || type === "number") return /_paise$/.test(name) ? 5_800_000 : /(^|_)(id|pk)$/.test(name) ? 3 : 1;
  if (type === "string") {
    if (s.format === "date") return "2026-10-01";
    if (s.format === "date-time") return "2026-10-01T09:30:00.000Z";
    if (/_date$|^date_/.test(name)) return "2026-10-01";
    if (/_at$/.test(name)) return "2026-10-01T09:30:00.000Z";
    if (/email/.test(name)) return "meera.pillai@example.com";
    if (/amount|_paise$/.test(name)) return "58000.00";
    if (/currency/.test(name)) return "INR";
    if (/^next_after$|cursor/.test(name)) return "1042";
    return name ? `<${name}>` : "<string>";
  }
  return null;
}

/** A short type name: string, integer, Money, "a" | "b", array of X. */
function typeOf(s: JsonSchema, defs: Record<string, JsonSchema> = {}): string {
  if (s.$ref) return s.$ref.split("/").pop()!;
  if (s.id) return s.id;
  if (s.enum) return s.enum.map((v) => `\`${String(v)}\``).join(" \\| ");
  if (s.anyOf) {
    const parts = s.anyOf.filter((p) => p.type !== "null").map((p) => typeOf(p, defs));
    return parts.join(" or ") + (s.anyOf.some((p) => p.type === "null") ? ", or null" : "");
  }
  if (s.type === "array" && s.items) return `array of ${typeOf(s.items, defs)}`;
  if (Array.isArray(s.type)) return s.type.filter((t) => t !== "null").join(" or ") + (s.type.includes("null") ? ", or null" : "");
  if (s.format === "date") return "date";
  if (s.format === "date-time") return "timestamp";
  return s.type ?? "any";
}

const cell = (text: string) => text.replace(/\|/g, "\\|").replace(/\n+/g, " ");

function fieldTable(schema: JsonSchema, heading: string): string[] {
  const props = Object.entries(schema.properties ?? {});
  if (props.length === 0) return [];
  const required = new Set(schema.required ?? []);
  return [
    `| ${heading} | Type | Required | Notes |`,
    "| --- | --- | --- | --- |",
    ...props.map(([name, p]) => {
      const notes = [p.description ?? "", p.default !== undefined && p.default !== null ? `Default \`${JSON.stringify(p.default)}\`.` : ""]
        .filter(Boolean)
        .join(" ");
      return `| \`${name}\` | ${cell(typeOf(p))} | ${required.has(name) && p.default === undefined ? "yes" : ""} | ${cell(notes)} |`;
    }),
    "",
  ];
}

const anchor = (e: Endpoint) => `${e.method}-${e.path}`.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

export type Catalogues = {
  scopes: Record<string, string>;
  events: Record<string, { scope: string; description: string }>;
  problems: Record<string, string>;
  statuses: Record<string, number>;
};

export function endpointReference(endpoints: Endpoint[], c: Catalogues): string {
  const tags = [...new Set(endpoints.map((e) => e.tag))];
  const out: string[] = [];

  out.push("### Scopes", "", "| Scope | Lets the client |", "| --- | --- |");
  for (const [scope, text] of Object.entries(c.scopes)) out.push(`| \`${scope}\` | ${cell(text)} |`);
  out.push("", "### Event types", "", "| Type | Needs | Means |", "| --- | --- | --- |");
  for (const [type, e] of Object.entries(c.events)) out.push(`| \`${type}\` | \`${e.scope}\` | ${cell(e.description)} |`);
  out.push("", "### Error codes", "", "| Code | Status | Means |", "| --- | --- | --- |");
  for (const [code, text] of Object.entries(c.problems)) out.push(`| <a id="problem-${code}"></a>\`${code}\` | ${c.statuses[code]} | ${cell(text)} |`);
  out.push("", "### Endpoints", "");

  out.push("| Method | Path | Scopes | What it does |", "| --- | --- | --- | --- |");
  for (const e of endpoints) {
    const scopes = e.public ? "none (public)" : e.scopes.length ? e.scopes.map((s) => `\`${s}\``).join(" + ") : "any token";
    out.push(`| ${e.method} | [\`${e.path}\`](#${anchor(e)}) | ${scopes} | ${cell(e.summary)} |`);
  }
  out.push("");

  for (const tag of tags) {
    out.push(`### ${tag} endpoints`, "");
    for (const e of endpoints.filter((x) => x.tag === tag)) {
      out.push(`#### ${e.method} ${e.path}`, "", `<a id="${anchor(e)}"></a>**${e.summary}.**${e.description ? ` ${e.description}` : ""}`, "");
      const facts: string[] = [];
      if (e.public) facts.push("No token needed.");
      else if (e.scopes.length) facts.push(`Needs ${e.scopes.map((s) => `\`${s}\``).join(" and ")}.`);
      else facts.push("Any valid token.");
      if (e.optionalScopes?.length) facts.push(`More fields with ${e.optionalScopes.map((s) => `\`${s}\``).join(" or ")}.`);
      if (e.idempotent) facts.push("Send an `Idempotency-Key`.");
      if (e.etag) facts.push(e.method === "GET" ? "Returns an `ETag`." : "Returns an `ETag`; honours `If-Match`.");
      facts.push(`Answers ${e.status ?? 200}.`);
      out.push(facts.join(" "), "");

      if (e.params) {
        out.push("| Path parameter | Meaning |", "| --- | --- |", ...Object.entries(e.params).map(([k, v]) => `| \`${k}\` | ${cell(v)} |`), "");
      }
      if (e.query) out.push(...fieldTable(toJson(e.query), "Query parameter"));
      if (e.body) {
        const body = toJson(e.body);
        const resolved = body.$ref && body.$defs ? (body.$defs[body.$ref.split("/").pop()!] ?? body) : body;
        out.push(...fieldTable(resolved, "Body field"));
      }
      if (e.example?.body !== undefined || e.example?.path || e.example?.query) {
        const target = `${e.example?.path ?? e.path}${e.example?.query ? `?${e.example.query}` : ""}`;
        out.push("```http", `${e.method} /api/v1${target}`);
        if (e.example?.body !== undefined) out.push("Content-Type: application/json", "", JSON.stringify(e.example.body, null, 2));
        out.push("```", "");
      }
      // What comes back: the fields, then an example. Hand-written where the
      // endpoint defines one, otherwise built from its own response schema,
      // so every endpoint answers "what will I get?" and none can drift.
      if (e.produces) {
        out.push(`Answers with \`${e.produces}\` — the file itself, not JSON.`, "");
      } else if (e.status !== 204) {
        const response = toJsonOut(e.response);
        const defs = response.$defs ?? {};
        const resolved = deref(response, defs);
        const unwrapped = resolved.properties?.data ? deref(resolved.properties.data, defs) : null;
        const item = unwrapped?.type === "array" && unwrapped.items ? deref(unwrapped.items, defs) : unwrapped;
        if (item?.properties) out.push(...fieldTable(item, resolved.properties?.data && unwrapped?.type === "array" ? "Field, per item" : "Response field"));
        else if (resolved.properties) out.push(...fieldTable(resolved, "Response field"));
        const sample = e.example?.response !== undefined ? e.example.response : sampleOf(response, defs);
        out.push("```json", JSON.stringify(sample, null, 2), "```", "");
      }
    }
  }
  return out.join("\n").trimEnd() + "\n";
}

/** API.md with its reference section replaced. */
export function withReference(markdown: string, reference: string): string {
  const start = markdown.indexOf(REFERENCE_START);
  const end = markdown.indexOf(REFERENCE_END);
  if (start < 0 || end < start) throw new Error("API.md has lost its endpoint-reference markers.");
  return `${markdown.slice(0, start + REFERENCE_START.length)}\n\n${reference}\n${markdown.slice(end)}`;
}
